### ISSUE TITLE
ESP-IDF v5.0

### ISSUE THREAD

**Issue by tajnymag** [turgu1/ESP-IDF-InkPlate#13]
Due to some bugs that I've found in the esp_websocket_client, I've tried to update to esp-idf v5.0-beta1. Espressif migrated by default to C++20 and deprecated some components.

I have fixed all the issues causing the build process to fail and fixed most of the warnings as well as I could. In the current state the library is buildable with idf v5. I'll be doing further testing in my project and over the weekend I'll try to build the library back with idf v4.4.

The changes are currently in my [idf-v5,0-support branch](https://github.com/tajnymag/ESP-IDF-InkPlate/tree/idf-v5.0-support). Could you please create a branch to which I could create a pull request?

**Comment by turgu1** [comment]
Hello Marek, I've created branch idf-v5.0-support under v0.9.8. Hope it will be ok.
