### ISSUE TITLE
x509

### ISSUE THREAD

**Issue by lorenko** [turgu1/ESP-IDF-InkPlate#4]
I am trying the first examples and I am experiencing this problem with PlatformIO

` Executing task: platformio run --environment inkplate-10 <

Processing inkplate-10 (platform: espressif32; board: esp-wrover-kit; framework: espidf)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp-wrover-kit.html
PLATFORM: Espressif 32 (3.3.2) > Espressif ESP-WROVER-KIT
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (ftdi) On-board (ftdi) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-espidf 3.40300.0 (4.3.0) 
 - tool-cmake 3.16.4 
 - tool-esptoolpy 1.30100.210531 (3.1.0) 
 - tool-ninja 1.7.1 
 - toolchain-esp32ulp 1.22851.191205 (2.28.51) 
 - toolchain-xtensa32 2.80400.210211 (8.4.0)
Reading CMake configuration...
Generating assembly for certificate bundle...
CMake Error at /home/lorenko/.platformio/packages/framework-espidf/tools/cmake/scripts/data_file_embed_asm.cmake:26 (file):
  file failed to open for reading (No such file or directory):

    /home/lorenko/esp/ESP-IDF-InkPlate/examples/Basic_Inkplate_Functionality/Inkplate_basic_BW/.pio/build/inkplate-10/x509_crt_bundle

*** Error 1
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 1 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ESP-IDF-Inkplate> 0.9.4+sha.9365c7f
Building in release mode
*** [.pio/build/inkplate-10/.pio/build/inkplate-10/x509_crt_bundle.o] Source `.pio/build/inkplate-10/x509_crt_bundle.S' not found, needed by target `.pio/build/inkplate-10/.pio/build/inkplate-10/x509_crt_bundle.o'.
================================================================================================ [FAILED] Took 4.70 seconds ================================================================================================

Environment    Status    Duration
-------------  --------  ------------
inkplate-10    FAILED    00:00:04.696
========================================================================================== 1 failed, 0 succeeded in 00:00:04.696 ========================`

**Comment by turgu1** [comment]
Hello lorenko,
I don't really understand what you try to achieve. Are you trying to add x509 support to the Inkplate 10 device?
